version: 1.0.{build}
clone_folder: c:\gopath\src\github.com\twexler\octonotify
environment:
  GOPATH: c:\gopath
cache:
  - "vendor -> glide.lock"
build_script:
- cmd: >-
    choco install -y make

    make
artifacts:
- path: build/octonotify*.exe
  name: octonotify
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: g1pvtkff+IkhSeABhJ7uHAyHw9eNoshBRvx//ouuY0XiaybltXW5akOwLuzbIS4m
  artifact: build/octonotify*.exe
  draft: true
  on:
    appveyor_repo_tag: true
